language: node_js
node_js:
    - "stable"
    - "4.6.0"
services: mongodb
env:
  global:
  - CXX: g++-4.8
  - TWILIO_APP_SID: somenotr3al4pps1dgoeshere
  - MONGO_URL: mongodb://localhost/call-tracking
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
